### ISSUE TITLE
problem after arduinoJson Update

### ISSUE THREAD

**Issue by spilz87** [andrasbiro/ArduCastControl#2]
Hello,

just to share I had issue with new ArduinoJson library to compile (V6.20).

I solved it by replacing in ArduCastControl.cpp
`as<char*>`
by
`as<const char*>`

Now it compile, I need to test to confirm

**Comment by andrasbiro** [comment]
I don't work on this currently, so it would make it difficult to test - but I'm happy to merge it if you create a pull request.

**Comment by spilz87** [comment]
After test this modification works well. 

I will try to pull a request for it :)
